### ISSUE TITLE
Question] Is it possible on ubuntu 14.04?

### ISSUE THREAD

**Issue by YongseopKim** [JosephWoodward/VSCodeILViewer#15]
Hello.

I'm trying this VSCodeILViewer on ubuntu 14.04, but facing this error message.

```
command 'extension.showIlWindow' not found
```

Anything to install dependent package?

**Comment by YongseopKim** [comment]
Additinally, my installed program(VSCodeILViewer) version is 0.0.1.

**Comment by tanaka-takayoshi** [comment]
The same issue occurs on my RHEL 7.3 Server with GUI. Is it only supported Windows?

**Comment by josephwoodward** [comment]
Hi, thank you for reporting this. It should work on Windows, Mac and Linux, though I've only verified it on Windows and Mac.

Does your project target the `project.json` format?

Also, could you do me a favour and go to VS Code > Help > Toggle Developer Tools and tell me what the console says? You should see some errors in there.

Thanks

**Comment by YongseopKim** [comment]
Thank you for your answer.

My console message (You can ignore the files(conv_ovf_r8_i*). I removed them, tested again, and then reached the same result.)
```
Failed to watch /home/dragon/.config/Code/User for configuration changes (Error: watch /home/dragon/.config/Code/User ENOSPC)
ipc.cp.ts:152[IPC Library: Watcher] Error: watch /home/dragon/nfs/sample/test-il ENOSPC(anonymous function) @ ipc.cp.ts:152
ipc.cp.ts:152[IPC Library: Watcher] Error: watch /home/dragon/nfs/sample/test-il/Program.cs ENOSPC(anonymous function) @ ipc.cp.ts:152
ipc.cp.ts:152[IPC Library: Watcher] Error: watch /home/dragon/nfs/sample/test-il/conv_ovf_r8_i.exe ENOSPC(anonymous function) @ ipc.cp.ts:152
ipc.cp.ts:152[IPC Library: Watcher] Error: watch /home/dragon/nfs/sample/test-il/conv_ovf_r8_i.il ENOSPC(anonymous function) @ ipc.cp.ts:152
ipc.cp.ts:152[IPC Library: Watcher] Error: watch /home/dragon/nfs/sample/test-il/project.json ENOSPC(anonymous function) @ ipc.cp.ts:152
ipc.cp.ts:152[IPC Library: Watcher] Error: watch /home/dragon/nfs/sample/test-il/project.lock.json ENOSPC(anonymous function) @ ipc.cp.ts:152
mime.ts:59Overwriting extension <<.s>> to now point to mime <<text/x-arm>>
mime.ts:59Overwriting extension <<.S>> to now point to mime <<text/x-arm>>
extensionHost.ts:282[Extension Host] Activating extension `josephwoodward.vscodeilviewer` failed: Cannot find module './logger'.d.logExtensionHostMessage @ extensionHost.ts:282
extensionHost.ts:282[Extension Host] Activating extension `josephwoodward.vscodeilviewer` failed:  Cannot find module './logger'd.logExtensionHostMessage @ extensionHost.ts:282
extensionHost.ts:282[Extension Host] Here is the error stack:  Error: Cannot find module './logger'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Function.V.o._load (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:14:30928)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/dragon/.vscode/extensions/josephwoodward.vscodeilviewer-0.0.1/out/src/extension.js:4:18)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
mainThreadExtensionService.ts:110Activating extension `josephwoodward.vscodeilviewer` failed: Cannot find module './logger'.t.$localShowMessage @ mainThreadExtensionService.ts:110
3extensionHost.ts:282[Extension Host] _isHugeProject = false (0)
messageService.ts:126command 'extension.showIlWindow' not found: Error: command 'extension.showIlWindow' not found
    at t._tryExecuteCommand (file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:64:14712)
    at file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:64:14551
    at then (file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:19172)
    at t.executeCommand (file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:64:14525)
    at t.run (file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:51:29261)
    at t.run (file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:51:29609)
    at e.runAction (file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:95:4317)
    at click (file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:95:4087)
    at CallbacksRegistry.apply (/usr/share/code/resources/electron.asar/common/api/callbacks-registry.js:54:39)
    at EventEmitter.<anonymous> (/usr/share/code/resources/electron.asar/renderer/api/remote.js:282:21)e.doShow @ messageService.ts:126
extensionHost.ts:282 [Extension Host] ApplicationInsights:Sender [Object]
```

dotnet version
```
~/nfs/sample/test-il ᐅ dotnet --version
1.0.0-preview2-1-003177
```

Program.cs
```c#
using System;

namespace ConsoleApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
}
```

project.json
```js
{
  "version": "1.0.0-*",
  "buildOptions": {
    "debugType": "portable",
    "emitEntryPoint": true
  },
  "dependencies": {},
  "frameworks": {
    "netcoreapp1.1": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.1.0"
        }
      },
      "imports": "dnxcore50"
    }
  }
}
```

**Comment by YongseopKim** [comment]
I'm not sure @tanaka-takayoshi 's environment is the same as mine.

**Comment by josephwoodward** [comment]
Thanks for the console output, it looks like it's something to do with the logger:

```
extensionHost.ts:282[Extension Host] Activating extension `josephwoodward.vscodeilviewer` failed: Cannot find module './logger'.d.logExtensionHostMessage @ extensionHost.ts:282
extensionHost.ts:282[Extension Host] Activating extension `josephwoodward.vscodeilviewer` failed:  Cannot find module './logger'd.logExtensionHostMessage @ extensionHost.ts:282
extensionHost.ts:282[Extension Host] Here is the error stack:  Error: Cannot find module './logger'
```

I'll have to see if I can spin up a VM and replicate the issue, thank you for reporting it.

**Comment by tanaka-takayoshi** [comment]
Hi @JosephWoodward , my RHEL 7.3 outputs the same error message.

**Comment by josephwoodward** [comment]
Ok, thanks @tanaka-takayoshi I will try get around to this as soon as I can. In the mean time, thank you for making me aware of the issue.

**Comment by tanaka-takayoshi** [comment]
[Updated]
@JosephWoodward I found one thing. The file name "Logger" starts with Upper case, but required path "logger" starts with lower case.
https://github.com/JosephWoodward/VSCodeILViewer/blob/master/src/vscodeilviewer/src/extension.ts#L5
https://github.com/JosephWoodward/VSCodeILViewer/blob/master/src/vscodeilviewer/src/Logger.ts
I edited extension.js under my local directory (~/.vscode-insiders/extensions/josephwoodward.vscodeilviewer-0.0.1/out/src) and reloaded plugin, the ILViewer windows opened and successfully displayed the IL codes!!

Also, you built ilViewer.WebApi.dll with .NET Core 1.0, didn't you? When I used .NET Core 1.1, "Inspecting IL, hold onto your seat belts!" message has been displaying more than 30 minutes. After I changed to .NET Core 1.0, everything works well.
